# Generated by Django 2.2.6 on 2019-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
