# Generated by Django 2.2.6 on 2019-12-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_clock_tocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='name',
            field=models.CharField(default='Clock', max_length=150),
        ),
        migrations.AlterField(
            model_name='clock',
            name='ticks',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
